INSERT INTO smn_pagos.smn_solicitud_documento
(
	smn_solicitud_documento_id,
	smn_documento_id,
	sdp_numero_solicitud_pago,
	smn_rol_id,
	smn_entidad_bancaria_rf,
	smn_cuenta_bancaria_rf,
	smn_usuario_id,
	smn_clave_formato_impresion_id,
	sdp_fecha_solicitud,
	sdp_numero,
	sdp_idioma,
	sdp_usuario,
	sdp_fecha_registro,
	sdp_hora
)
VALUES
(
	${seq:currval@smn_pagos.seq_smn_solicitud_documento},
	${fld:smn_documento_id},
	${seq:currval@smn_pagos.seq_smn_numero_solicitud_pago},
	${fld:smn_rol_id},
	${fld:smn_entidad_bancaria_rf},
	${fld:smn_cuenta_bancaria_rf},
	${fld:smn_usuario_id},
	${fld:smn_clave_formato_impresion_id},
	${fld:sdp_fecha_solicitud},
	${fld:sdp_numero},
	'${def:locale}',
	'${def:user}',
	'${def:date}',
	'${def:time}'
)
