INSERT INTO smn_pagos.smn_anticipo
(
	smn_anticipo_id,
	smn_entidad_rf,
	smn_sucursal_rf,
	smn_proveedor_rf,
	smn_documento_id,
	ant_numero_documento,
	smn_orden_compra_rf,
	ant_porcentaje,
	ant_monto_ml,
	ant_monto_ma,
	ant_estatus,
	smn_usuario_solicitante_rf,
	smn_usuario_aprobador_rf,
	smn_moneda_rf,
	smn_tasa_rf,
	ant_idioma,
	ant_usuario,
	ant_fecha_registro,
	ant_hora
)
VALUES
(
	${seq:currval@smn_pagos.seq_smn_anticipo},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_proveedor_rf},
	${fld:smn_documento_id},
	${fld:ant_numero_documento},
	${fld:smn_orden_compra_rf},
	${fld:ant_porcentaje},
	${fld:ant_monto_ml},
	${fld:ant_monto_ma},
	${fld:ant_estatus},
	${fld:smn_usuario_solicitante_rf},
	${fld:smn_usuario_aprobador_rf},
	${fld:smn_moneda_rf},
	${fld:smn_tasa_rf},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
